<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>VtfMaximumLab</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="AssemblyInfo.cs" />
    <ProjectReference Include="..\..\GmodAddonCompressor-master\GmodAddonCompressor\GmodAddonCompressor.csproj" />
  </ItemGroup>
</Project>
